-- Copyright 2015 Novartis Institutes for Biomedical Research
-- 
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
-- 
--     http://www.apache.org/licenses/LICENSE-2.0
-- 
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.

INSERT INTO CURATOR (
  CURATOR_ID, 
  USERNAME, 
  IS_ACTIVE, 
  CREATED_BY) 
VALUES (
  PRIMARY_KEY_SEQ.nextval, 
  'SYSTEM', 
  1, 
  PRIMARY_KEY_SEQ.CURRVAL);
 
INSERT INTO VERSION (
  VERSION_ID, 
  CREATED_BY)
VALUES (
  PRIMARY_KEY_SEQ.nextval,
  (SELECT CURATOR_ID FROM CURATOR WHERE USERNAME='SYSTEM'));
  
INSERT INTO RELATIONSHIP_TYPE (
  RELATIONSHIP_TYPE_ID,
  RELATIONSHIP_TYPE,
  NAME,
  DEFINTION,
  IS_CYCLIC,
  IS_SYMMETRIC,
  IS_TRANSITIVE,
  EDGE_COLOUR,
  STATUS,
  CREATED_BY,
  CREATED_VERSION_ID,
  APPROVED_VERSION_ID
) VALUES (
  PRIMARY_KEY_SEQ.nextval,
  'is_a',
  'is a',
  'Subclassing relationship between one term and another',
  0,
  0,
  1,
  '#29477F',
  'APPROVED',
  (SELECT CURATOR_ID FROM CURATOR WHERE USERNAME='SYSTEM'),
  (SELECT MAX(VERSION_ID) FROM VERSION),
  (SELECT MAX(VERSION_ID) FROM VERSION));
 
INSERT INTO RELATIONSHIP_TYPE (
  RELATIONSHIP_TYPE_ID,
  RELATIONSHIP_TYPE,
  NAME,
  DEFINTION,
  IS_CYCLIC,
  IS_SYMMETRIC,
  IS_TRANSITIVE,
  STATUS,
  CREATED_BY,
  CREATED_VERSION_ID,
  APPROVED_VERSION_ID
) VALUES (
  PRIMARY_KEY_SEQ.nextval,
  'union_of',
  'union of',
  'Represents the union of several other terms',
  0,
  0,
  0,
  'APPROVED',
  (SELECT CURATOR_ID FROM CURATOR WHERE USERNAME='SYSTEM'),
  (SELECT MAX(VERSION_ID) FROM VERSION),
  (SELECT MAX(VERSION_ID) FROM VERSION));
  
INSERT INTO RELATIONSHIP_TYPE (
  RELATIONSHIP_TYPE_ID,
  RELATIONSHIP_TYPE,
  NAME,
  DEFINTION,
  IS_CYCLIC,
  IS_SYMMETRIC,
  IS_TRANSITIVE,
  STATUS,
  CREATED_BY,
  CREATED_VERSION_ID,
  APPROVED_VERSION_ID
) VALUES (
  PRIMARY_KEY_SEQ.nextval,
  'disjoint_from',
  'disjoint from',
  'Terms have no instances or subclasses in common',
  0,
  1,
  0,
  'APPROVED',
  (SELECT CURATOR_ID FROM CURATOR WHERE USERNAME='SYSTEM'),
  (SELECT MAX(VERSION_ID) FROM VERSION),
  (SELECT MAX(VERSION_ID) FROM VERSION));

INSERT INTO RELATIONSHIP_TYPE (
  RELATIONSHIP_TYPE_ID,
  RELATIONSHIP_TYPE,
  NAME,
  DEFINTION,
  IS_CYCLIC,
  IS_SYMMETRIC,
  IS_TRANSITIVE,
  EDGE_COLOUR,
  STATUS,
  CREATED_BY,
  CREATED_VERSION_ID,
  APPROVED_VERSION_ID
) VALUES (
  PRIMARY_KEY_SEQ.nextval,
  'part_of',
  'part of',
  'Subpart relationship between one term and another',
  0,
  0,
  1,
  '#923222',
  'APPROVED',
  (SELECT CURATOR_ID FROM CURATOR WHERE USERNAME='SYSTEM'),
  (SELECT MAX(VERSION_ID) FROM VERSION),
  (SELECT MAX(VERSION_ID) FROM VERSION));
  
INSERT INTO RELATIONSHIP_TYPE (
  RELATIONSHIP_TYPE_ID,
  RELATIONSHIP_TYPE,
  NAME,
  DEFINTION,
  IS_CYCLIC,
  IS_SYMMETRIC,
  IS_TRANSITIVE,
  EDGE_COLOUR,
  STATUS,
  CREATED_BY,
  CREATED_VERSION_ID,
  APPROVED_VERSION_ID
) VALUES (
  PRIMARY_KEY_SEQ.nextval,
  'develops_from',
  'develops from',
  'Anatomical structures change through development',
  0,
  0,
  1,
  '#329222',
  'APPROVED',
  (SELECT CURATOR_ID FROM CURATOR WHERE USERNAME='SYSTEM'),
  (SELECT MAX(VERSION_ID) FROM VERSION),
  (SELECT MAX(VERSION_ID) FROM VERSION));  

INSERT INTO DATASOURCE (
  DATASOURCE_ID,
  DATASOURCE_NAME,
  DATASOURCE_ACRONYM,
  DATASOURCE_URI,
  IS_INTERNAL,
  IS_PUBLIC,
  CREATED_BY
) VALUES (
  PRIMARY_KEY_SEQ.NEXTVAL,
  'Clinical Data Interchange Standards Consortium',
  'CDISC',
  'http://www.cdisc.org',
  0,
  1,
  (SELECT CURATOR_ID FROM CURATOR WHERE USERNAME='SYSTEM'));
  
INSERT INTO DATASOURCE (
  DATASOURCE_ID,
  DATASOURCE_NAME,
  DATASOURCE_ACRONYM,
  DATASOURCE_URI,
  IS_INTERNAL,
  IS_PUBLIC,
  CREATED_BY
) VALUES (
  PRIMARY_KEY_SEQ.NEXTVAL,
  'Standard for Exchange of Nonclinical Data',
  'SEND',
  'http://www.cdisc.org/send',
  0,
  1,
  (SELECT CURATOR_ID FROM CURATOR WHERE USERNAME='SYSTEM'));
  
INSERT INTO DATASOURCE (
  DATASOURCE_ID,
  DATASOURCE_NAME,
  DATASOURCE_ACRONYM,
  DATASOURCE_URI,
  IS_INTERNAL,
  IS_PUBLIC,
  CREATED_BY
) VALUES (
  PRIMARY_KEY_SEQ.NEXTVAL,
  'National Cancer Institution Thesaurus',
  'NCI',
  'http://ncit.nci.nih.gov',
  0,
  1,
  (SELECT CURATOR_ID FROM CURATOR WHERE USERNAME='SYSTEM'));

INSERT INTO DATASOURCE (
  DATASOURCE_ID,
  DATASOURCE_NAME,
  DATASOURCE_ACRONYM,
  DATASOURCE_URI,
  IS_INTERNAL,
  IS_PUBLIC,
  CREATED_BY
) VALUES (
  PRIMARY_KEY_SEQ.NEXTVAL,
  'Medical Dictionary for Regulatory Activities',
  'MedDRA',
  'http://www.meddramsso.com',
  0,
  1,
  (SELECT CURATOR_ID FROM CURATOR WHERE USERNAME='SYSTEM'));
  
INSERT INTO DATASOURCE (
  DATASOURCE_ID,
  DATASOURCE_NAME,
  DATASOURCE_ACRONYM,
  DATASOURCE_URI,
  IS_INTERNAL,
  IS_PUBLIC,
  CREATED_BY
) VALUES (
  PRIMARY_KEY_SEQ.NEXTVAL,
  'International Harmonization of Nomenclature and Diagnostic',
  'INHAND',
  'http://www.toxpath.org/inhand.asp',
  0,
  1,
  (SELECT CURATOR_ID FROM CURATOR WHERE USERNAME='SYSTEM'));

INSERT INTO DATASOURCE (
  DATASOURCE_ID,
  DATASOURCE_NAME,
  DATASOURCE_ACRONYM,
  DATASOURCE_URI,
  IS_INTERNAL,
  IS_PUBLIC,
  CREATED_BY
) VALUES (
  PRIMARY_KEY_SEQ.NEXTVAL,
  'Medical Subject Headings',
  'MeSH',
  'http://www.nlm.nih.gov/mesh/',
  0,
  1,
  (SELECT CURATOR_ID FROM CURATOR WHERE USERNAME='SYSTEM'));

INSERT INTO DATASOURCE (
  DATASOURCE_ID,
  DATASOURCE_NAME,
  DATASOURCE_ACRONYM,
  DATASOURCE_URI,
  IS_INTERNAL,
  IS_PUBLIC,
  CREATED_BY
) VALUES (
  PRIMARY_KEY_SEQ.NEXTVAL,
  'Systematized Nomenclature of Medicine',
  'SNOMED',
  'http://www.ihtsdo.org/snomed-ct',
  0,
  1,
  (SELECT CURATOR_ID FROM CURATOR WHERE USERNAME='SYSTEM'));
  
  
INSERT
INTO ONTOLOGY
  (
    ONTOLOGY_ID,
    ONTOLOGY_NAME,
    DESCRIPTION,
    IS_INTERNAL,
    SOURCE_NAMESPACE,
    SOURCE_URI,
    SOURCE_RELEASE,
    SOURCE_FORMAT,
    REFERENCE_ID_PREFIX,
    REFERENCE_ID_VALUE,
    IS_CODELIST,
    STATUS,
    CREATED_DATE,
    CREATED_BY,
    CREATED_VERSION_ID,
    APPROVED_VERSION_ID
  )
  VALUES
  (
    1,
    'OWL',
    'The OWL 2 Schema vocabulary (OWL 2)',
    '1',
    'owl',
    'http://www.w3.org/2002/07/owl',
    'http://www.w3.org/2002/07/owl',
    'RDF/OWL',
    'owl',
    '1',
    '0',
    'APPROVED',
    TO_DATE('2017-07-14 12:38:54', 'YYYY-MM-DD HH24:MI:SS'),
    (SELECT CURATOR_ID FROM CURATOR WHERE USERNAME='SYSTEM'),
    (SELECT MAX(VERSION_ID) FROM VERSION),
    (SELECT MAX(VERSION_ID) FROM VERSION)
  );

INSERT
INTO TERM
  (
    TERM_ID,
    ONTOLOGY_ID,
    TERM_NAME,
    REFERENCE_ID,
    DEFINITION_URL,
    COMMENTS,
    IS_ROOT,
    STATUS,
    CREATED_DATE,
    CREATED_BY,
    CREATED_VERSION_ID,
    APPROVED_VERSION_ID
  )
  VALUES
  (
    1,
    1,
    'Thing',
    'Thing',
    'http://www.w3.org/2002/07/owl#Thing',
    'The class of OWL individuals.',
    '1',
    'APPROVED',
    TO_DATE('2017-07-14 12:49:19', 'YYYY-MM-DD HH24:MI:SS'),
    (SELECT CURATOR_ID FROM CURATOR WHERE USERNAME='SYSTEM'),
    (SELECT MAX(VERSION_ID) FROM VERSION),
    (SELECT MAX(VERSION_ID) FROM VERSION)
  );
